import { TimelineEvent, VideoItem, QuoteItem, ThemeItem, SummaryItem } from './types';

export const INTRO_TEXT = `This is a collection of summaries of videos from the history of computers that address the future humanity and the relationship of people and computers. It was generated by Google AI Studio from YouTube links using a prompt.

Prompt and video selection by Dominik Lukeš, all text (except intro comments to sections) generated by Gemini 2.5 Pro via Google AI Studio on 3 Aug 2025.

Note: I did not check all quotes in the transcript for accuracy but I watched all the videos and they seem broadly correct. A few spot checks did not reveal any problems. I also removed all text where the model is saying ‘sure, I’ll do this for you’.`;

export const TIMELINE_DATA: TimelineEvent[] = [
  { year: "1946", title: "ENIAC Newsreel", description: "Introduction of the first electronic computer for military problems.", quote: "Are people becoming obsolete?" },
  { year: "1956", title: "Integrated Data Processing", description: "Showcases electromechanical machines automating clerical tasks.", quote: "A telling blow at the increasing volume and cost of paperwork." },
  { year: "1960", title: "Logistic Support Management", description: "Details the USAF's use of an IBM 705 for 'management by exception.'", quote: "It required human judgments, human decisions to solve this special and complex problem." },
  { year: "1962", title: "IBM 7030 STRETCH", description: "Documents the supercomputer as a tool for scientists.", quote: "[Scientists now have] a tool powerful enough to... simulate how the earth weather really behaves." },
  { year: "1963", title: "The Big Switch", description: "IBM demonstrates replacing a manual system with a computer.", quote: "By 1962, the capacity of the [manual] system had been reached." },
  { year: "1968", title: "Man and Computer - A Perspective", description: "An IBM film framing the computer as a tool to handle fact-based tasks, augmenting human intellect.", quote: "Today, the computer can provide an enormous extension of his mental powers." },
  { year: "1972", title: "Career Training Film", description: "Portrays computer jobs as an upwardly mobile career path.", quote: "Promotion is to more complex assignments... and with more study, to programmer." },
  { year: "1976", title: "Basic Computer Terms", description: "Aims to demystify computers, framing them as manageable tools.", quote: "Computers don't think. It's us people who do the thinking." },
  { year: "1983", title: "The Computer Chronicles - Fifth Generation", description: "Explores early AI and expert systems.", quote: "We regard these expert systems as assistants to human professionals." }
];

export const VIDEO_LIST: VideoItem[] = [
  { id: "1", title: "ENIAC Newsreel", year: "1946", description: "A newsreel introducing the ENIAC, the world's first electronic computer, highlighting its raw calculation speed for military problems and hinting at future civilian use.", link: "https://www.youtube.com/watch?v=OSYpYFEwr4o" },
  { id: "2", title: "Integrated Data Processing", year: "1956", description: "A business film showcasing how electromechanical machines using punched paper tape can automate repetitive clerical tasks like order entry and invoicing.", link: "https://www.youtube.com/watch?v=iu9wFTKkgS4" },
  { id: "3", title: "Logistic Support Management for Advanced Weapons", year: "1960", description: "A U.S. Air Force film detailing the use of an IBM 705 mainframe to automate missile supply logistics, enabling \"management by exception.\"", link: "https://www.youtube.com/watch?v=l9Luktdq9pc" },
  { id: "4", title: "IBM 7030 STRETCH Photos & Film Excerpts", year: "1962", description: "A documentary on the transistor-based STRETCH supercomputer, a powerful tool designed to augment the work of scientists on massive problems like weather forecasting.", link: "https://www.youtube.com/watch?v=9AHZnwQ2-3o" },
  { id: "5", title: "\"The Big Switch\": The Story of Improved Message Control", year: "1963", description: "An IBM film demonstrating the replacement of a manual message-switching center with a computer-controlled system, shifting human roles from manual labor to system oversight.", link: "https://youtu.be/irPw9oyAju8" },
  { id: "6", title: "Man and Computer : A Perspective", year: "c. 1968", description: "A film by IBM United Kingdom that presents the computer as a tool to extend human mental capabilities by handling logical, fact-based tasks, thereby freeing humans for creative and subjective pursuits.", link: "https://www.youtube.com/watch?v=BUCZJWo9MZo" },
  { id: "7", title: "A Brief Excerpt from a Career Training Film", year: "1972", description: "A career guidance film portraying computer-related jobs (keypunch, console operator) as an upwardly mobile extension of the clerical field.", link: "https://www.youtube.com/watch?v=eorxtvnyGBY" },
  { id: "8", title: "Basic Computer Terms", year: "1976", description: "An educational film that demystify mainframe computers for beginners, framing them as manageable tools that augment human efficiency.", link: "https://www.youtube.com/watch?v=q-gpM-KfVng" },
  { id: "9", title: "The Computer Chronicles - Fifth Generation", year: "1983", description: "An episode exploring the dawn of Artificial Intelligence and \"expert systems,\" presenting the computer as a \"knowledge processor\" and an intelligent assistant to human professionals.", link: "https://youtu.be/Mu8zyHh4vTg" }
];

export const QUOTES_DATA: QuoteItem[] = [
  {
    videoTitle: "ENIAC Newsreel", year: "1946",
    quotes: [
      { text: "Are people becoming obsolete? The giant electronic brain has started cogitating at the University of Pennsylvania.", timecode: "0:02", link: "https://www.youtube.com/watch?v=OSYpYFEwr4o&t=2s" },
      { text: "...who knows, someday a machine like this may check up on your income tax.", timecode: "0:46", link: "https://www.youtube.com/watch?v=OSYpYFEwr4o&t=46s" }
    ]
  },
  {
    videoTitle: "Integrated Data Processing", year: "1956",
    quotes: [
      { text: "Business management finally has a way to strike a telling blow at the increasing volume and cost of paperwork.", timecode: "2:05", link: "https://www.youtube.com/watch?v=iu9wFTKkgS4&t=125s" },
      { text: "The system allows management to make decisions based on current facts, not past history.", timecode: "25:58", link: "https://www.youtube.com/watch?v=iu9wFTKkgS4&t=1558s" }
    ]
  },
  {
    videoTitle: "Logistic Support Management for Advanced Weapons", year: "1960",
    quotes: [
      { text: "Electronic data processing takes care of all routine transactions... The machine...recognizes problems it cannot solve: the exceptional situations. It calls attention to these problems by making a printout on the high-speed printer.", timecode: "13:04", link: "https://www.youtube.com/watch?v=l9Luktdq9pc&t=784s" },
      { text: "It required human technical skills, human judgments, human decisions to solve this special and complex problem. This is management by exception.", timecode: "16:09", link: "https://www.youtube.com/watch?v=l9Luktdq9pc&t=969s" }
    ]
  },
  {
    videoTitle: "IBM 7030 STRETCH Photos & Film Excerpts", year: "1962",
    quotes: [
      { text: "[Scientists now have] a tool powerful enough to take the complicated equations and simulate how the earth weather really behaves, all within the computer.", timecode: "10:41", link: "https://www.youtube.com/watch?v=9AHZnwQ2-3o&t=641s" },
      { text: "[The operator uses the console where] switches make it possible for him to vary the course of the computer.", timecode: "9:34", link: "https://www.youtube.com/watch?v=9AHZnwQ2-3o&t=574s" }
    ]
  },
  {
    videoTitle: "\"The Big Switch\": The Story of Improved Message Control", year: "1963",
    quotes: [
      { text: "By 1962, the capacity of the [manual] system had been reached. It lacked the capability to handle future requirements.", timecode: "3:09", link: "https://youtu.be/irPw9oyAju8&t=189s" }
    ]
  },
  {
    videoTitle: "Man and Computer: A Perspective", year: "1968",
    quotes: [
      { text: "In the Industrial Revolution, machines multiplied the power of his hands. Today, the computer can provide an enormous extension of his mental powers.", timecode: "1:16", link: "https://www.youtube.com/watch?v=BUCZJWo9MZo&t=76s" },
      { text: "But in the realm of facts, where there is only one possible answer... where human qualities such as imagination and foresight are not required, computers are a priceless tool.", timecode: "1:40", link: "https://www.youtube.com/watch?v=BUCZJWo9MZo&t=100s" }
    ]
  },
  {
    videoTitle: "A Brief Excerpt from a Career Training Film", year: "1972",
    quotes: [
      { text: "Opportunities are good... to advance to better paying jobs, even to supervisory or managerial positions.", timecode: "2:17", link: "https://www.youtube.com/watch?v=eorxtvnyGBY&t=137s" },
      { text: "Promotion is to more complex assignments, to supervisor, and with more study, to programmer.", timecode: "5:55", link: "https://www.youtube.com/watch?v=eorxtvnyGBY&t=355s" }
    ]
  },
  {
    videoTitle: "Basic Computer Terms", year: "1976",
    quotes: [
      { text: "This machine cannot do anything that people cannot do... Only the truth is, the computer can do it about a zillion times faster.", timecode: "4:52", link: "https://www.youtube.com/watch?v=q-gpM-KfVng&t=292s" },
      { text: "Computers don't think. It's us people who do the thinking. Computers simply process the data that you give them, and they process it in the way you tell them.", timecode: "14:15", link: "https://www.youtube.com/watch?v=q-gpM-KfVng&t=855s" }
    ]
  },
  {
    videoTitle: "The Computer Chronicles - Fifth Generation", year: "1983",
    quotes: [
      { text: "We regard these expert systems as assistants to human professionals, and we believe that they will not be used unless they can explain to the human user how they are reasoning.", timecode: "19:31", link: "https://youtu.be/Mu8zyHh4vTg&t=1171s" },
      { text: "[The expert system was created because there were] too few experts in the world in order to capture and diagnose all the problems encountered by the drilling teams.", timecode: "14:04", link: "https://youtu.be/Mu8zyHh4vTg&t=844s" }
    ]
  }
];

export const THEMES_DATA: ThemeItem[] = [
  {
    title: "1. The Computer as a Tool for Efficiency and Control",
    description: "This is the most persistent and practical view of computers. It frames them not as a philosophical threat, but as an essential instrument for overcoming the logistical and financial burdens of modern complexity. This sentiment sees the computer as a solution to problems of scale that have overwhelmed manual, human-powered systems.",
    examples: [
      { context: "In Business (1956)", quote: "Business management finally has a way to strike a telling blow at the increasing volume and cost of paperwork.", source: "Integrated Data Processing (1956)" },
      { context: "In Communications (1963)", quote: "By 1962, the capacity of the [manual] system had been reached. It lacked the capability to handle future requirements.", source: "\"The Big Switch\" (1963)" },
      { context: "In General Use (1976)", quote: "This machine cannot do anything that people cannot do... Only the truth is, the computer can do it about a zillion times faster.", source: "Basic Computer Terms (1976)" }
    ]
  },
  {
    title: "2. The Human is the Irreplaceable Thinker",
    description: "This perspective is a direct counter-narrative to the fear of human obsolescence. It establishes a clear and reassuring hierarchy: machines are powerful servants that handle mechanical processes, but humans possess the unique and irreplaceable capacity for judgment, intuition, and strategic thought. The machine can process, but only the human can truly *decide*.",
    examples: [
      { context: "In Military Logistics (1960)", quote: "It required human technical skills, human judgments, human decisions to solve this special and complex problem. This is management by exception.", source: "Logistic Support Management (1960)" },
      { context: "In Philosophical Framing (c. 1968)", quote: "But in the realm of facts, where there is only one possible answer... where human qualities such as imagination and foresight are not required, computers are a priceless tool.", source: "Man and Computer : A Perspective (c. 1968)" },
      { context: "In Public Education (1976)", quote: "Computers don't think. It's us people who do the thinking. Computers simply process the data that you give them, and they process it in the way you tell them.", source: "Basic Computer Terms (1976)" },
      { context: "In the Dawn of AI (1983)", quote: "...they will not be used unless they can explain to the human user how they are reasoning.", source: "The Computer Chronicles - Fifth Generation (1983)" }
    ]
  },
  {
    title: "3. The Computer as an Amplifier of Human Potential",
    description: "This sentiment views the computer as a transformative partner that doesn't just make old work faster, but makes entirely new achievements possible. It's about augmenting and extending human capabilities, allowing individuals to tackle previously insurmountable problems, amplifying the knowledge of experts, and creating entirely new avenues for career advancement.",
    examples: [
      { context: "In Scientific Research (1962)", quote: "[Scientists now have] a tool powerful enough to take the complicated equations and simulate how the earth weather really behaves...", source: "IBM 7030 STRETCH (1962)" },
      { context: "In Conceptual Thinking (c. 1968)", quote: "In the Industrial Revolution, machines multiplied the power of his hands. Today, the computer can provide an enormous extension of his mental powers.", source: "Man and Computer : A Perspective (c. 1968)" },
      { context: "In the Workforce (1972)", quote: "Promotion is to more complex assignments, to supervisor, and with more study, to programmer.", source: "A Brief Excerpt from a Career Training Film (1972)" },
      { context: "In Professional Practice (1983)", quote: "[The expert system was created because there were] too few experts in the world in order to capture and diagnose all the problems...", source: "The Computer Chronicles - Fifth Generation (1983)" }
    ]
  }
];

export const SUMMARIES_DATA: SummaryItem[] = [
  {
    id: "summary-1",
    title: "Introducing the ENIAC in 1946",
    metadata: {
      originalTitle: "1946 ENIAC computer - Movietone News",
      date: "1946",
      link: "https://www.youtube.com/watch?v=OSYpYFEwr4o",
      authors: "Movietone",
      commissioningAgency: "Movietone News"
    },
    sections: [
        {
            title: "Video description",
            content: "A newsreel shows people operating the ENIAC computer.<br/><br/><blockquote>Are people becoming obsolete? The giant electronic brain has started cogitating at the University of Pennsylvania. It's made of vacuum tubes like your radio, and it can add up a column of figures a yard long in a second.</blockquote><br/>A newsreel shows the different components of the ENIAC.<br/><br/><blockquote>It's the world's first electronic computer. Right now, it's solving mathematical problems for the US Army, but who knows, someday a machine like this may check up on your income tax.</blockquote>"
        }
    ]
  },
  {
    id: "summary-2",
    title: "Integrated Data Processing (1956)",
    metadata: {
        originalTitle: "Office Automation Computers: Integrated Data Processing 1956 IBM Burroughs NCR ELECOM Bell Teletype",
        date: "Circa 1956",
        link: "https://www.youtube.com/watch?v=iu9wFTKkgS4",
        authors: "Narrated and presented by Dr. Robert A. Scudder. Filmed by News Reel Laboratories.",
        commissioningAgency: "National Office Management Association (NOMA)"
    },
    sections: [
      {
        title: "Video description",
        content: "This 1956 film, produced by the National Office Management Association (NOMA), introduces the concept of \"Integrated Data Processing\" (IDP). It presents IDP as a revolutionary business technique to combat the rising volume and cost of paperwork. The film argues that by capturing data once at its source using \"common language machines\" (primarily via punched paper tape or cards), businesses can automate repetitive clerical tasks, reduce costly transcription errors, speed up document processing, and provide management with more timely and accurate reports for better decision-making."
      },
      {
        title: "Processes described",
        content: "<ul><li><strong>Order Entry:</strong> A sales order is received and processed. Instead of being manually re-typed at each stage, its data is captured once on a punched paper tape.</li><li><strong>Manufacturing & Shipping:</strong> The initial paper tape is used to automatically generate manufacturing orders, shipping documents, bills of lading, and packing slips.</li><li><strong>Invoicing:</strong> Data from the original order tape, combined with manual inputs for quantities shipped, is used to automatically calculate and print customer invoices.</li><li><strong>Accounting and Reporting:</strong> The same data, captured as a by-product on tape or punched cards, is then used for downstream processes like accounts receivable, sales analysis, inventory control, and commission reports.</li></ul>"
      },
      {
        title: "Human jobs and their roles described",
        content: "<ul><li><strong>Pre-IDP Role (Typist/Clerk):</strong> The primary role was repetitive data transcription. The film highlights the inefficiency of this process: \"Usually, typists preparing manufacturing orders type the same information that was previously written by the salesman.\" This manual re-entry was slow and prone to error: \"Another costly effect of past procedures is transcription errors... one company reported an error rate of 30%.\"</li><li><strong>Post-IDP Role (Machine Operator):</strong> The human role shifts from being the data processor to the operator of the data processing system. The operator is responsible for initiating the process, handling the physical media (tapes and cards), and entering only the new, variable information that the machine cannot know. For example, after a master tape automatically types a customer's address, the operator manually types in the new order number and date.</li></ul>"
      },
      {
        title: "Use of computers",
        content: "The film showcases a variety of electromechanical \"common language machines\":<br/><br/><ul><li><strong>Burroughs Sensimatic to Tape:</strong> A complex accounting machine connected to a \"Perforator Program Console\" which punches information onto paper tape.</li><li><strong>Wheeldex Simplafind Tape Storage Unit:</strong> A mechanized system of trays containing master paper tapes for quick retrieval.</li><li><strong>Bell System Teletypewriter (Model 19):</strong> A teletype machine with an integrated transmitter-distributor and typing reperforator.</li><li><strong>IBM Cardatype Accounting Machine:</strong> A central console flanked by two IBM electric typewriters and a card sorter/punch unit.</li><li><strong>Friden Computyper Model C:</strong> An electric typewriter combined with a calculator keypad and paper tape reader/punch.</li><li><strong>Underwood ELECOM Computer Model 50:</strong> Billed as the \"FIRST ELECTRONIC ACCOUNTING MACHINE,\" consisting of several desk-sized units.</li></ul>"
      },
      {
        title: "Discussion of the roles of people alongside computers",
        content: "The video presents Integrated Data Processing not as a means to replace humans entirely, but to augment their productivity by eliminating the most tedious, repetitive, and error-prone aspects of their work. The core idea is to free up clerical workers from manual transcription so they can focus on oversight and handling exceptions.<br/><br/>The narrator frames the technology as a solution to a business problem, stating that business management finally has a way to \"strike a telling blow at the increasing volume and cost of paperwork.\" The ultimate goal is a synergistic relationship where machines handle high-volume, repetitive tasks, while humans provide the initial data, handle variable inputs, and use the final, timely reports for higher-level decision-making."
      }
    ]
  },
  {
      id: "summary-3",
      title: "Logistic Support Management for Advanced Weapons (1960)",
      metadata: {
          originalTitle: "1957 - 1960's IBM 705 Mainframe Computer Data Processing- USAF Military Punch Card, Educational",
          date: "1960",
          link: "https://www.youtube.com/watch?v=l9Luktdq9pc",
          authors: "Charles Cahill & Associates, Inc.",
          commissioningAgency: "United States Air Force, Air Photographic and Charting Service (MATS)"
      },
      sections: [
          { title: "Video description", content: "This 1960 U.S. Air Force film details the logistics and supply chain management system for \"advanced weapon systems,\" specifically strategic ballistic missiles. The film highlights the transition from manual, time-consuming processes to a new, computer-driven system that uses an IBM 705 mainframe to manage inventory, track parts, and automate resupply. The central theme is \"management by exception.\"" },
          { title: "Processes described", content: "The film describes the logistics process for responding to a missile component failure:<br/><ol><li><strong>Malfunction and Request:</strong> A countdown is halted. \"A missile must stand waiting for the right part, in the right place, at the right time.\"</li><li><strong>Emergency Response:</strong> A designated \"expediter officer\" initiates action.</li><li><strong>Data Entry:</strong> The supply transaction is recorded. \"Without data processing, it could have taken hours or days... Now it can be recorded in minutes.\"</li><li><strong>Punch Card Creation:</strong> An operator creates a transaction card from a master card.</li><li><strong>Computer Analysis:</strong> The IBM 705 updates master files and checks stock levels.</li><li><strong>Management by Exception:</strong> \"The machine...recognizes problems it cannot solve: the exceptional situations. It calls attention to these problems by making a printout.\"</li><li><strong>Human Decision-Making:</strong> A human manager analyzes the report and makes a decision.</li></ol>" },
          { title: "Human jobs and their roles described", content: "<ul><li><strong>Launch Control Officers:</strong> Monitor status and initiate supply chain.</li><li><strong>Supply and Expediter Officers:</strong> Manage local stock and coordinate delivery.</li><li><strong>Keypunch and Verifier Operators:</strong> Create and verify punch cards.</li><li><strong>Computer Operators:</strong> Operate the mainframe, load tapes, and monitor the console.</li><li><strong>Logistics Managers:</strong> Review \"exception reports\" to solve complex problems.</li></ul>" },
          { title: "Use of computers", content: "<ul><li><strong>IBM 705 Mainframe:</strong> The \"nerve center,\" shown as large grey cabinets with vacuum tubes.</li><li><strong>IBM 705 Console:</strong> A large desk-like unit with a typewriter and indicator lights.</li><li><strong>IBM 727 Magnetic Tape Units:</strong> Cabinets containing large spinning reels of magnetic tape.</li><li><strong>High-Speed Printer:</strong> Generates long reports for managers.</li></ul>" },
          { title: "Discussion of the roles of people alongside computers", content: "The film presents the computer not as a replacement for human workers, but as a powerful tool that <strong>augments</strong> their capabilities. The core concept is \"management by exception,\" where the computer handles routine tasks, freeing human managers for judgment and analysis.<br/><br/><blockquote>\"Electronic data processing takes care of all routine transactions in each of these functional areas.\"</blockquote><br/><blockquote>\"It required human technical skills, human judgments, human decisions to solve this special and complex problem. This is management by exception.\"</blockquote>" }
      ]
  },
  {
      id: "summary-4",
      title: "IBM 7030 STRETCH Photos & Film Excerpts (1962)",
      metadata: {
          originalTitle: "Computer History: World's FASTEST Computer! 1961-1964 film & photos",
          date: "1962 (Source)",
          link: "https://www.youtube.com/watch?v=9AHZnwQ2-3o",
          authors: "The Computer History Archives Project (CHAP)",
          commissioningAgency: "IBM (original footage)"
      },
      sections: [
          { title: "Video description", content: "This video details the history of the IBM 7030 STRETCH supercomputer. It places STRETCH in the context of its predecessors and explains the technological leap from vacuum tubes to transistors. It features Stephen Dunwell, the Project Director, describing the architecture and its application in weather research." },
          { title: "Processes described", content: "<ul><li><strong>Large-Scale Scientific Computation:</strong> Used by NASA, MIT, Bell Labs.</li><li><strong>Military and Defense Calculations:</strong> The IBM NORC was built for the US Navy.</li><li><strong>Atmospheric Modeling:</strong> Using STRETCH for \"testing mathematical models of the earth's atmosphere\" to predict weather patterns.</li></ul>" },
          { title: "Human jobs and their roles described", content: "<ul><li><strong>Computer Operator:</strong> Interactions include flipping switches and mounting tapes. \"The lady can tell what's going on by watching the numbers.\"</li><li><strong>Project Director:</strong> Leads design and development.</li><li><strong>Engineers:</strong> Designing, building, and inspecting components like transistor circuit cards.</li><li><strong>Scientists/Researchers:</strong> End-users using the system to \"advance man's understanding of why the atmosphere behaves the way it does.\"</li></ul>" },
          { title: "Use of computers", content: "<ul><li><strong>IBM 704 & NORC:</strong> Shown with large consoles and vacuum tubes.</li><li><strong>IBM STRETCH (7030):</strong> A massive room-filling installation with sleek gray cabinets. Key components include \"Transistor Circuit Cards,\" the \"Instruction Unit,\" and the \"Look-Ahead\" feature. It was capable of \"more than one billion... operations every second.\"</li></ul>" },
          { title: "Discussion of the roles of people alongside computers", content: "The video portrays computers as powerful augmentative tools.<br/><br/><strong>Humans as Operators:</strong> \"The lights permit the operator to ascertain the course of the job... Switches make it possible for him to vary the course of the computer.\"<br/><br/><strong>Tools for Understanding:</strong> Scientists now have \"a tool powerful enough to take the complicated equations and simulate how the earth weather really behaves.\"<br/><br/><strong>Collaboration:</strong> The work is described in human terms, framing the output as a productivity gain that allows scientists to achieve previously impossible results." }
      ]
  },
  {
      id: "summary-5",
      title: "\"The Big Switch\": The Story of Improved Message Control (1963)",
      metadata: {
          originalTitle: "1963 Rare IBM Film: \"The Big Switch\" and 1410 Data Processing System",
          date: "1963",
          link: "https://youtu.be/irPw9oyAju8",
          authors: "IBM Data Processing Division",
          commissioningAgency: "IBM"
      },
      sections: [
          { title: "Video description", content: "This film details the challenge of internal corporate communications and presents a computer-based solution. IBM explains the limitations of its previous manual \"torn-tape\" message switching system and introduces its new, computer-controlled \"Internal Tele-Processing System\" (I-T-P-S)." },
          { title: "Processes described", content: "<strong>The \"Torn-Tape\" Switching Center (Before):</strong> Manual reception on punched tape, tearing, logging, sorting, and physical retransmission.<br/><br/><strong>The Internal Tele-Processing System (After):</strong> Messages are punched offline, transmitted to the computer, converted to binary, stored in a disk file, and automatically forwarded when lines are free." },
          { title: "Human jobs and their roles described", content: "<strong>Pre-Computer Roles:</strong> Office workers, switchboard operators, and especially \"torn-tape switching center operators\" whose job was physically managing paper tape.<br/><br/><strong>Computer-Era Roles:</strong> Programmers, technicians, terminal operators, and system operators monitoring the computer's output." },
          { title: "Use of computers", content: "<ul><li><strong>IBM 1410 Data Processing System:</strong> The central computer.</li><li><strong>IBM 1301/1302 Disk File:</strong> Large storage units for messages.</li><li><strong>IBM 729 Magnetic Tape Drives:</strong> For long-term storage.</li><li><strong>IBM Program Transmission Control Unit:</strong> Converts telegraph code to computer binary code.</li></ul>" },
          { title: "Discussion of the roles of people alongside computers", content: "The video suggests computers were necessary to overcome physical limitations, augmenting organizational capability while replacing specific manual jobs.<br/><br/>The computer directly <strong>replaces</strong> the jobs of the torn-tape operators. However, it <strong>augments</strong> human capabilities by creating roles in system design, oversight, and data input. The shift is described as moving from a system limited by human speed to one powered by the \"speed and capacity... power and flexibility\" of electronic computers." }
      ]
  },
  {
      id: "summary-6",
      title: "Man and Computer : A Perspective (1967)",
      metadata: {
          originalTitle: "Man and Computer : A Perspective",
          date: "c. 1968",
          link: "https://www.youtube.com/watch?v=BUCZJWo9MZo",
          authors: "Written and Directed by Peter de Normanville",
          commissioningAgency: "IBM United Kingdom"
      },
      sections: [
          { title: "Video description", content: "This film contrasts the subjective, creative nature of humans with the logical capabilities of computers. It breaks down basic computer functions using analogies and argues that while computers are powerful tools, they lack originality and judgment." },
          { title: "Processes described", content: "The video uses a \"human computer\" analogy to solve a problem (calculating average age). It breaks the process down into Store, Add, Divide, Print, and Stop instructions." },
          { title: "Human jobs and their roles described", content: "The film conceptualizes computer functions by assigning roles: Input, Store/Memory, Calculator, Output, and Control (directing others). It also shows programmers and operators." },
          { title: "Use of computers", content: "Computers are described as tools for tasks where \"facts are facts.\" Visuals include mainframe computers, punched cards, magnetic ring core memory, and various output devices." },
          { title: "Discussion of the roles of people alongside computers", content: "The film emphasizes that computers augment human capabilities.<br/><br/><blockquote>\"In the Industrial Revolution, machines multiplied the power of his hands. Today, the computer can provide an enormous extension of his mental powers.\"</blockquote><br/>It distinguishes roles: \"Humans are artistic, fallible, inventive, original,\" while computers are for tasks where \"human qualities such as imagination and foresight are not required.\" It concludes: \"Computers have no originality... only men and women can ensure that this city of the future will be a place of beauty.\"" }
      ]
  },
  {
      id: "summary-7",
      title: "A Brief Excerpt from a Career Training Film (1972)",
      metadata: {
          originalTitle: "Vintage Computers: 1972 Office Automation, Clerical Careers",
          date: "c. 1972",
          link: "https://www.youtube.com/watch?v=eorxtvnyGBY",
          authors: "Ralph Lopatin Productions, Inc.",
          commissioningAgency: "U.S. Department of Defense"
      },
      sections: [
          { title: "Video description", content: "This career training film highlights how traditional office jobs are evolving with computers. It presents the \"clerical field\" as a gateway to well-paying careers, emphasizing that new technologies create opportunities for advancement." },
          { title: "Processes described", content: "Transitions from manual typing and bookkeeping to keypunching, data typing, and computer operation. It shows various duplication and mail processing machines." },
          { title: "Human jobs and their roles described", content: "Jobs listed include File Clerk, Typist, Bookkeeper, and machine-oriented roles like Keypunch Operator and Computer Console Operator. It mentions paths to Programmer or Department Head." },
          { title: "Use of computers", content: "Shows a UNIVAC 9400 Console, magnetic tape drives, card readers, and line printers. Data input devices include keypunch machines and early video display terminals." },
          { title: "Discussion of the roles of people alongside computers", content: "The theme is that automation <strong>augments and creates jobs</strong>. It emphasizes upward mobility: \"Opportunities are good... to advance to better paying jobs.\" Humans remain essential operators; the film never depicts a fully automated data center. It presents a ladder of skills where mastering one machine leads to more complex assignments." }
      ]
  },
  {
      id: "summary-8",
      title: "Basic Computer Terms (1976)",
      metadata: {
          originalTitle: "Basic Computer Terms (1976)",
          date: "1976",
          link: "https://www.youtube.com/watch?v=q-gpM-KfVng",
          authors: "Renan Productions",
          commissioningAgency: "Educational/Training"
      },
      sections: [
          { title: "Video description", content: "This educational film follows Harry, a skeptical businessman, guided by Jane, a computer expert. It introduces fundamental concepts like hardware, software, and input/output to alleviate fears about computers \"taking over.\"" },
          { title: "Processes described", content: "<strong>Hardware vs. Software:</strong> Physical machine vs. instructions.<br/><strong>Data:</strong> Information the program works on.<br/><strong>Four Basic Functions:</strong> Input, Processing, Memory, Output.<br/><strong>Bugs:</strong> Mistakes in the program." },
          { title: "Human jobs and their roles described", content: "<strong>Businessman:</strong> Needs solution for paperwork.<br/><strong>Computer Expert:</strong> Bridge between technology and user.<br/><strong>Operators:</strong> Keypunch and Computer operators managing hardware.<br/><strong>End-Users:</strong> Professionals like editors and airline agents." },
          { title: "Use of computers", content: "Shows mid-70s tech: IBM System/370 mainframes, IBM 3420 tape drives, magnetic disk packs, keypunch machines, teletype terminals, and CRT terminals." },
          { title: "Discussion of the roles of people alongside computers", content: "The film confronts the fear of replacement. Jane explains: \"This machine cannot do anything that people cannot do... Only the truth is, the computer can do it about a zillion times faster.\" It emphasizes human control: \"Computers don't think. It's us people who do the thinking.\"" }
      ]
  },
  {
      id: "summary-9",
      title: "The Computer Chronicles - Fifth Generation (1983)",
      metadata: {
          originalTitle: "The Computer Chronicles - Fifth Generation Computers",
          date: "1983",
          link: "https://youtu.be/Mu8zyHh4vTg",
          authors: "Hosts: Stewart Cheifet and Gary Kildall",
          commissioningAgency: "KCSM-TV"
      },
      sections: [
          { title: "Video description", content: "This episode explores \"Fifth Generation\" computing, focusing on AI and expert systems. It discusses \"knowledge processing\" and the role of knowledge engineers." },
          { title: "Processes described", content: "<strong>Generational Evolution:</strong> From hardware changes to \"knowledge information processing systems.\"<br/><strong>Knowledge Engineering:</strong> Building human expertise into a computer.<br/><strong>Rule-Based Reasoning:</strong> Using \"if-then\" rules and backward chaining." },
          { title: "Human jobs and their roles described", content: "<strong>Human Expert:</strong> Provides specialized \"heuristic knowledge.\"<br/><strong>Knowledge Engineer:</strong> Translates reasoning into rules.<br/><strong>Professional User:</strong> Uses the system as an assistant." },
          { title: "Use of computers", content: "Contrasts older automated systems (Robot Tape Librarian) with intelligent ones (Drilling Advisor Expert System) that use windowed interfaces to show dialogue and reasoning." },
          { title: "Discussion of the roles of people alongside computers", content: "Expert systems are framed as tools that <strong>augment</strong> human capabilities. \"We regard these expert systems as assistants to human professionals.\" It emphasizes transparency: users must be able to understand the system's reasoning. The goal is to distribute scarce human expertise." }
      ]
  }
];

export const METHOD_PROMPTS = {
  timeline: [
    { label: "First prompt", text: "Make a mermaid timeline of these with computer, year of video, subject" },
    { label: "Follow up prompt", text: "add one key quote to the mermaid timeline as a separate block" }
  ],
  videos: [
    { label: "Prompt", text: "Make a short Markdown list of all videos with linked title, year, short description." }
  ],
  quotes: [
    { label: "Prompt", text: "Now, pull out key quotes from each video that exemplifies attitude to people being replaced by machines - the format should be: \n\n## Video title (Year)\n\" quote text [time code linked to video]\n\nMake it 1-3 quotes per video maximum" }
  ],
  themes: [
    { label: "First prompt", text: "Try to identify and illustrate three to five key sentiments or perspectives contained within these." },
    { label: "Follow up prompt", text: "Don't try to think of the sentiments chronologically. Imagine these are not distinguished by time. Each must be represented by more than one video and have more than one quote to illustrate." }
  ],
  summaries: [
    { label: "Prompt", text: "Take this video and describe in detail: \n\n1. Who, what and when\n2. Role of computers in this change\n3. Computers replacing or augmenting humans\n\nSupport everything with quotes and describe what the computers and processes looked like.\n\nLink all quotes to timecodes (using Markdown)\n\nComplete this template:\n\n## Video title\n\n### Video metadata\n- Title (retrieve from the URL)\n- Date\n- Link\n- Authors\n- Commissioning agency\n\n### Video description\n[what the video is about]\n\n### Processes described\n\n### Human jobs and their roles described\n\n### Use of computers (including descriptions of visuals)\n\n### Discussion of the roles of people alongside computers\n[any questions about the role of humans in computer age, support with quotes]" }
  ]
};
